#!/usr/bin/env python3
"""Apply comprehensive, non-destructive Chinese and bilingual localization to LiveContainer and embedded SideStore.

Design Principles:
- Zero-intrusion: Does NOT touch any Storyboard XML files (preserves all controls, actions, and segues).
- Zero-intrusion: Does NOT modify any Swift/Objective-C/C source files (preserves all logic, closures, and UI aesthetics).
- Zero test violation: Resides under .github/scripts/ to keep scripts/ whitelist intact for tests/test_repository.py.
- Comprehensive coverage: Translates all v3 Unified Shell components (Setup Assistant, SideStore host management,
  Refresh Manager, Backups, Certificates, Anisette, JIT, Tweaks, Guest controls, and dialogs).
"""
from __future__ import annotations

import json
from pathlib import Path
import shutil
import sys

# Comprehensive Simplified Chinese mapping for Unified v3 Shell, Settings, and Host Components
V3_TRANSLATIONS: dict[str, str] = {
    # 1. Unfinished upstream keys
    "lc.appSettings.classicModeDesc": "（实验性）引导系统以合适的分辨率显示该应用。在 iPadOS 上，若应用原生不支持 iPad，将以 iPhone 模式显示。",
    "lc.appSettings.selected32BitEmulator": "32 位模拟器",
    "lc.settings.selected32BitEmulator": "默认 32 位模拟器",

    # 2. General Navigation & Actions
    "Home": "首页",
    "About": "关于",
    "Actions": "操作",
    "Active": "已激活",
    "Inactive": "未激活",
    "Completed": "已完成",
    "None": "无",
    "Notice": "提示",
    "OK": "好",
    "Cancel": "取消",
    "Confirm": "确认",
    "Done": "完成",
    "Delete": "删除",
    "Delete Selected": "删除所选项",
    "Delete from Device": "从设备中删除",
    "Clear All": "全部清除",
    "Clear Selection": "清除选择",
    "Clear Download Cache": "清理下载缓存",
    "Save": "保存",
    "Restore": "恢复",
    "Restore Backup": "恢复备份",
    "Retry": "重试",
    "Retry Connection": "重试连接",
    "Open": "打开",
    "Open Settings": "打开设置",
    "Open Refresh Manager": "打开刷新管理器",
    "Later": "稍后",
    "Submit": "提交",
    "Submit Code": "提交验证码",
    "Re-check": "重新检查",
    "Ready to use": "已就绪可用",
    "Reset to Defaults": "恢复默认设置",
    "Description": "描述",
    "Options": "选项",
    "State": "状态",
    "Status": "状态",
    "Status & Identity": "状态与标识",
    "Frequency": "频率",
    "Target time (local)": "目标时间（本地）",
    "Weekday": "星期",
    "Daily": "每天",
    "Weekly": "每周",
    "Every six hours": "每 6 小时",
    "GET": "获取",
    "Install": "安装",
    "Installed": "已安装",
    "Update": "更新",
    "Update Channel": "更新通道",
    "Leave empty for the default channel.": "留空则使用默认通道。",
    "Keep All": "保留全部",
    "Keep Existing": "保留现有",

    # 3. Setup Assistant (开机向导)
    "Setup": "配置",
    "Setup Assistant": "开机配置向导",
    "Setup Complete": "配置完成",
    "Finish Setup": "完成配置",
    "Account, pairing and a verified refresh are all in place.": "Apple 账户、设备配对与刷新验证均已就绪。",
    "Copy Setup Diagnostics": "复制向导诊断",
    "Cancel Test": "取消测试",
    "Run Test Refresh": "运行测试刷新",

    # 4. Account and Signing (账户与签名)
    "Account and Signing": "账户与签名",
    "Apple Account": "Apple 账户",
    "Apple ID": "Apple ID",
    "Sign In": "登录",
    "Sign In / Re-authenticate": "登录 / 重新验证",
    "Sign Out": "退出登录",
    "Cancel Sign In": "取消登录",
    "Continue to Sign In": "继续登录",
    "Signed in": "已登录",
    "Signing": "应用签名",
    "Signing Status": "签名状态",
    "Team": "开发团队",
    "Teams": "开发团队列表",
    "Developer Team": "开发团队",
    "Developer Portal": "开发者门户",
    "Developer Services": "开发者服务",
    "Import Account": "导入账户",
    "Export Account": "导出账户",
    "Export Account File": "导出账户文件",
    "Include Apple Password": "包含 Apple 密码",
    "Step 1 - Choose how Apple sends your code:": "步骤 1 - 选择 Apple 发送验证码的方式：",
    "Step 2 - Enter the code you received:": "步骤 2 - 输入收到的验证码：",
    "That was not accepted. Check the Apple ID and password, then submit again.": "验证未通过。请检查 Apple ID 与密码后重新提交。",

    # 4a. Unified v3 sign-in, authentication recovery, and two-factor prompts
    "Apple ID Sign In": "Apple ID 登录",
    "Enter the Apple ID and password used for signing.": "请输入用于签名的 Apple ID 和密码。",
    "Choose Verification Method": "选择验证方式",
    "Choose how Apple should send your verification code.": "选择 Apple 发送验证码的方式。",
    "Choose how Apple sends your verification code.": "选择 Apple 发送验证码的方式。",
    "Choose the phone number for this request.": "选择此次请求使用的电话号码。",
    "Verifying code...": "正在验证验证码…",
    "Requesting verification...": "正在请求验证…",
    "Choose a phone number for this verification request...": "请选择用于此次验证请求的电话号码…",
    "Technical details": "技术详情",
    "Use Trusted Device": "使用受信任设备",
    "Send SMS": "发送短信",
    "Request Voice Call": "请求语音来电",
    "Choose Phone Number": "选择电话号码",
    "Select where Apple should send the verification code.": "选择 Apple 发送验证码的电话号码。",
    "Enter Verification Code": "输入验证码",
    "Verification code": "验证码",
    "Verify Code": "验证代码",
    "Change Verification Method": "更改验证方式",
    "Verification complete": "验证完成",
    "Verification could not continue. You can change method or cancel sign-in.": "无法继续验证。您可以更改验证方式或取消登录。",
    "Sign-in was cancelled.": "登录已取消。",
    "Open Apple Account Repair": "打开 Apple 账户修复页面",
    "Account Attention Needed": "需要处理 Apple 账户",
    "Resolve the account issue shown by Apple before signing in again.": "请先按照 Apple 显示的提示解决账户问题，然后再重新登录。",
    "Re-sign Required": "需要重新签名",
    "Re-sign": "重新签名",
    "Outdated Anisette Server": "Anisette 服务器版本过旧",
    "The configured anisette server is outdated, which increases the risk of locking the account. Continue anyway?": "当前配置的 Anisette 服务器版本过旧，继续使用可能增加账户被锁定的风险。仍要继续吗？",
    "Sign-in diagnostics": "登录诊断信息",
    "Sign-in attempt could not be confirmed": "无法确认登录尝试是否完成",
    "Provisioning needs attention": "需要处理配置问题",
    "Provisioning could not be completed.": "无法完成配置。",
    "Begin Sign In": "开始登录",
    "Cancel Unconfirmed Sign-In": "取消未确认的登录",
    "Checking...": "正在检查…",
    "Reload Status": "重新加载状态",
    "Cancel the unconfirmed sign-in before retrying provisioning.": "重试配置前，请先取消尚未确认的登录。",
    "Retry Provisioning": "重试配置",
    "Finish Later": "稍后完成",
    "Another sign-in or provisioning attempt is still active. Wait for it to finish, then reload status.": "另一个登录或配置任务仍在运行。请等待其完成后重新加载状态。",
    "Finish Later, then reopen Account & Signing to sign in again before retrying provisioning.": "请稍后完成，然后重新打开“账户与签名”再次登录，再重试配置。",
    "Apple ID is signed in. Retry provisioning or finish later.": "Apple ID 已登录。您可以重试配置或稍后完成。",
    "Review the current Apple sign-in state": "查看当前 Apple 登录状态",
    "Next: Set Up JIT-Less": "下一步：设置免 JIT 模式",
    "LiveContainer needs a JIT-Less certificate configured before guest apps can launch on iOS 26 and later.": "在 iOS 26 及更高版本上启动容器应用前，需要为 LiveContainer 配置免 JIT 证书。",
    "Continue to JIT-Less Setup": "继续设置免 JIT 模式",
    "Sign In with Apple ID": "使用 Apple ID 登录",
    "Sign-In Status": "登录状态",
    "Verification response": "验证响应",
    "Sign-in runs entirely in this screen. Credentials and codes go to Apple through the SideStore service; no separate app opens.": "登录全程在此页面完成。凭据和验证码会通过 SideStore 服务发送给 Apple，不会打开其他应用。",
    "The verification code was not accepted. Enter a new code and try again.": "验证码未被接受。请输入新的验证码并重试。",
    "Too many authentication attempts. Apple is temporarily rate-limiting requests. Wait before trying again.": "登录尝试次数过多，Apple 暂时限制了请求。请稍后再试。",
    "Apple's authentication service is temporarily unavailable. Try again later.": "Apple 登录服务暂时不可用，请稍后重试。",
    "Apple's authentication service did not return a valid response. Try again later.": "Apple 登录服务未返回有效响应，请稍后重试。",
    "Authentication could not obtain valid Anisette data.": "无法获取有效的 Anisette 数据以完成身份验证。",
    "Authentication could not reach the required Apple service. Check the connection and try again.": "无法连接所需的 Apple 服务。请检查网络连接后重试。",
    "Authentication could not reach the required Apple service.": "无法连接所需的 Apple 服务。",
    "Apple requires attention on this account before signing in.": "此 Apple 账户需要先处理相关问题才能登录。",
    "Apple sign-in failed for an unknown typed reason.": "Apple 登录失败，原因无法识别。",
    "Apple sign-in returned an error that could not be safely classified.": "Apple 登录返回了无法安全分类的错误。",
    "Apple ID sign-in failed.": "Apple ID 登录失败。",
    "Anisette authentication infrastructure failure.": "Anisette 身份验证基础设施故障。",
    "Network error during authentication.": "身份验证期间发生网络错误。",
    "Account repair required.": "需要修复 Apple 账户。",
    "Account repair is required. Open the Apple Developer account to resolve.": "需要修复账户。请打开 Apple Developer 账户并处理相关问题。",
    "Signed in successfully.": "已成功登录。",
    "Apple ID signed in successfully.": "Apple ID 已成功登录。",
    "Sign-in timed out. Start a new sign-in when you are ready.": "登录已超时。准备好后请重新开始登录。",
    "That verification session expired. Start a new sign-in to request another verification code.": "验证会话已过期。请重新登录以获取新的验证码。",
    "The saved Apple session is no longer valid. Sign in again with this Apple ID.": "已保存的 Apple 会话已失效。请使用此 Apple ID 重新登录。",
    "The saved Apple session is no longer valid. Sign in again with this Apple ID before retrying setup.": "已保存的 Apple 会话已失效。请使用此 Apple ID 重新登录后再重试配置。",
    "Signed in successfully, but provisioning was cancelled before setup finished.": "已成功登录，但配置尚未完成便已取消。",
    "Signed in successfully, but provisioning could not be completed.": "已成功登录，但无法完成配置。",

    # 4b. Unified v3 Setup Assistant and repair guidance
    "App Running": "应用运行状态",
    "Developer Mode": "开发者模式",
    "Guidance only: keep Developer Mode on in iOS Settings. Setup continues regardless.": "仅供提示：请在 iOS“设置”中保持开发者模式开启。无论此项状态如何，配置都会继续。",
    "Show Pairing Setup": "显示配对设置",
    "Re-check Pairing": "重新检查配对",
    "JIT-Less Mode": "免 JIT 模式",
    "JIT-Less": "免 JIT",
    "Open JIT-Less Diagnose": "打开免 JIT 诊断",
    "Set Up JIT-Less": "设置免 JIT",
    "Refresh JIT-Less Certificate": "更新免 JIT 证书",
    "Open Certificates": "打开证书",
    "Open JIT-Less Setup": "打开免 JIT 设置",
    "Wi-Fi": "Wi-Fi",
    "VPN Tunnel": "VPN 隧道",
    "Opening LocalDevVPN…": "正在打开 LocalDevVPN…",
    "Open / Enable LocalDevVPN": "打开 / 启用 LocalDevVPN",
    "CoreDevice": "CoreDevice",
    "Background App Refresh": "后台 App 刷新",
    "Schedule": "计划",
    "Verification": "验证",
    "Test Refresh": "测试刷新",
    "Complete Pairing Setup before testing refresh.": "请先完成设备配对设置，再测试刷新。",
    "Still Needed": "仍需完成",
    "Copied": "已复制",
    "Ready": "就绪",
    "Action required": "需要操作",
    "Checking": "正在检查",
    "Running": "运行中",
    "Warning": "警告",
    "Failed": "失败",
    "Unavailable": "不可用",
    "App running": "应用正在运行",
    "Pairing file available": "配对文件可用",
    "Checking pairing file status": "正在检查配对文件状态",
    "Not signed in": "未登录",
    "Signed in, provisioning needs attention": "已登录，但需要处理配置问题",
    "Signed in without an active team": "已登录，但没有可用的团队",
    "Not required on this iOS version": "此 iOS 版本无需配置",
    "Could not verify JIT-Less certificate state": "无法验证免 JIT 证书状态",
    "Checking Wi-Fi…": "正在检查 Wi-Fi…",
    "Wi-Fi unavailable": "Wi-Fi 不可用",
    "Needs Wi-Fi first": "需要先连接 Wi-Fi",
    "Wi-Fi available": "Wi-Fi 可用",
    "Tunnel interface present (not a CoreDevice proof)": "已检测到隧道接口（不代表 CoreDevice 已验证）",
    "Tunnel not present": "未检测到隧道",
    "Background App Refresh available": "后台 App 刷新可用",
    "Background App Refresh denied": "后台 App 刷新权限已拒绝",
    "Background App Refresh restricted": "后台 App 刷新受到限制",
    "Background App Refresh state unknown": "后台 App 刷新状态未知",
    "Scheduled refresh disabled": "定时刷新已关闭",
    "No verified refresh in this session yet": "此会话中尚无已验证的刷新",
    "Test refresh could not be completed, and the cause is not known.": "无法完成测试刷新，且原因未知。",
    "Another refresh is already running. Test Refresh did not start.": "另一个刷新任务正在运行，测试刷新尚未启动。",
    "Wait for the current refresh to finish, then start Test Refresh again.": "请等待当前刷新完成，然后再次启动测试刷新。",
    "Place or import a valid pairing file, then try again.": "请放置或导入有效的配对文件，然后重试。",
    "No verified result yet. Check Refresh Manager for progress.": "尚无已验证的结果。请在刷新管理器中查看进度。",
    "Refresh did not start.": "刷新未能启动。",
    "Open Refresh Manager to inspect this run, then try Test Refresh again. Copy Diagnostics if the result remains unclear.": "请打开刷新管理器检查此次运行，然后重试测试刷新。如果结果仍不明确，请复制诊断信息。",
    "SideStore reported that refresh completed, but this run's result could not be verified.": "SideStore 报告刷新已完成，但无法验证此次运行的结果。",
    "Open Refresh Manager to reconcile the run, then run Test Refresh again. Copy Diagnostics if the result remains missing.": "请打开刷新管理器核对此次运行，然后再次测试刷新。如果仍无结果，请复制诊断信息。",
    "Refresh verified": "刷新已验证",
    "Stopped waiting. The current refresh continues in the background.": "已停止等待；当前刷新仍会在后台继续。",
    "Check Refresh Manager before starting another Test Refresh.": "开始另一次测试刷新前，请先检查刷新管理器。",
    "Tap Test Refresh again to resume this same request; it will not start a duplicate refresh.": "再次轻点“测试刷新”即可继续同一请求，不会启动重复刷新。",
    "Verified by successful refresh": "已通过成功刷新验证",
    "Checked after a successful refresh": "将在成功刷新后检查",
    "Last verified refresh: none": "上次已验证刷新：无",
    "Product: ": "产品：",
    "iOS: ": "iOS：",
    "Pairing: ": "配对：",
    "Account: ": "账户：",
    "Team: ": "团队：",
    "Wi-Fi: ": "Wi-Fi：",
    "VPN interface: ": "VPN 接口：",
    "CoreDevice: ": "CoreDevice：",
    "Refresh schedule: ": "刷新计划：",
    "Last verified refresh: ": "上次已验证刷新：",

    # 4c. v3 certificate and account repair actions
    "Sign In to Manage Certificates": "登录以管理证书",
    "Sign In to Load Developer Data": "登录以加载开发者数据",
    "Sign In to Check Account Health": "登录以检查账户状态",
    "Use App-Specific Password": "使用 App 专用密码",
    "Begin Sign-In After Repair": "修复后开始登录",
    "Open Apple Account": "打开 Apple 账户",
    "Apple did not accept the Apple ID or password. Check them and try again.": "Apple 不接受此 Apple ID 或密码。请检查后重试。",
    "Apple requires an app-specific password for this authentication path.": "此身份验证方式需要 Apple App 专用密码。",
    "The developer portal request was malformed.": "开发者门户请求格式不正确。",
    "Apple did not accept the Apple ID or password.": "Apple 不接受此 Apple ID 或密码。",
    "No Apple Developer team is available for this account.": "此账户没有可用的 Apple Developer 团队。",
    "Create or join an Apple Developer team for this Apple ID before retrying.": "请先为此 Apple ID 创建或加入 Apple Developer 团队，然后重试。",

    # 4d. Dynamic v3 authentication prompt labels and recovery guidance
    "Details": "详情",
    "Continue": "继续",
    "Input Needed": "需要输入",
    "Start New Sign-In": "开始新的登录",
    "Check Password and Start New Sign-In": "检查密码并重新登录",
    "Start New Sign-In to Enter a New Code": "重新登录并输入新验证码",
    "Try Sign-In Again": "再次尝试登录",
    "Retry Cancellation": "重试取消",
    "Cancelling...": "正在取消…",
    "Select Team": "选择团队",
    "Choose the development team used for signing.": "请选择用于签名的开发者团队。",
    "Verification request sent to your trusted devices.": "验证请求已发送到受信任设备。",
    "Verification code requested by SMS.": "已请求通过短信发送验证码。",
    "Verification call requested.": "已请求语音验证码来电。",
    "The verification code was not accepted.": "验证码未被接受。",
    "Enter a fresh verification code when asked, then retry.": "系统再次提示时请输入新的验证码，然后重试。",
    "Two-factor authentication is required to continue.": "需要完成双重认证才能继续。",
    "Complete two-factor authentication, then retry.": "请完成双重认证，然后重试。",
    "Provisioning was cancelled.": "配置已取消。",
    "Run the operation again when ready.": "准备好后请重新运行此操作。",
    "The authentication handshake with Apple failed.": "与 Apple 的身份验证握手失败。",
    "Check the account sign-in state before retrying.": "重试前请检查账户登录状态。",
    "Valid Anisette data could not be obtained.": "无法获取有效的 Anisette 数据。",
    "You can retry; if it keeps failing, check the Anisette servers.": "您可以重试；如果问题持续，请检查 Anisette 服务器设置。",
    "The developer team has reached its development certificate limit.": "此开发者团队已达到开发证书数量上限。",
    "Revoke an unused certificate under Certificates before retrying.": "请先在“证书”中吊销未使用的证书，然后重试。",
    "Apple is temporarily limiting authentication or developer portal requests.": "Apple 暂时限制了身份验证或开发者门户请求。",
    "Wait before trying again.": "请稍后再试。",
    "Apple requires attention on this account before provisioning can continue.": "此 Apple 账户需要先处理相关问题才能继续配置。",
    "Resolve the account issue with Apple before retrying.": "请先按照 Apple 的提示解决账户问题，然后重试。",
    "The two-factor authentication response was not valid.": "双重认证响应无效。",
    "Start sign-in again so a fresh verification can complete.": "请重新开始登录，以完成新一轮验证。",
    "The developer portal request failed for an unknown reason.": "开发者门户请求失败，原因未知。",
    "You can retry; if it keeps failing, check the connection and try again later.": "您可以重试；如果问题持续，请检查网络并稍后再试。",
    "The provisioning request was malformed.": "配置请求格式不正确。",
    "Retry will repeat the same failure. Check the app configuration before trying again.": "重试可能会再次遇到相同错误。请先检查应用配置。",
    "Signing in again with the correct credentials is required before retrying.": "重试前需要使用正确的凭据重新登录。",
    "Join or create a developer team for this Apple ID before retrying.": "重试前请使用此 Apple ID 加入或创建开发者团队。",
    "Create an app-specific password for this Apple ID, then use it for this sign-in path.": "请为此 Apple ID 创建 App 专用密码，并在此登录流程中使用。",
    "This device could not be identified for registration.": "无法识别此设备以进行注册。",
    "Retry will repeat the same failure until the device identifier issue is resolved.": "在设备标识问题解决前，重试会再次失败。",
    "This device is already registered with the selected developer team.": "此设备已在所选开发者团队中注册。",
    "No action is needed for the device itself; retry continues provisioning.": "无需对设备本身进行操作；重试即可继续配置。",
    "Apple rejected the development certificate request.": "Apple 拒绝了开发证书请求。",
    "Check the team certificates before retrying.": "重试前请检查团队证书。",
    "The selected development certificate no longer exists on the Apple Developer account.": "所选开发证书已不在此 Apple Developer 账户中。",
    "Choose or create a current certificate before retrying.": "重试前请选择或创建有效证书。",
    "An App ID name was rejected as invalid.": "App ID 名称无效，已被拒绝。",
    "Fix the app identifier configuration before retrying.": "重试前请修正应用标识符配置。",
    "An app bundle identifier was rejected as invalid.": "应用的 Bundle ID 无效，已被拒绝。",
    "Fix the bundle identifier before retrying.": "重试前请修正 Bundle ID。",
    "Apple could not register this app identifier for the selected team.": "Apple 无法为所选团队注册此应用标识符。",
    "Use a different identifier or team before retrying.": "重试前请改用其他标识符或团队。",
    "A required App ID no longer exists on the developer team.": "开发者团队中缺少所需的 App ID。",
    "Recreate the App ID or sync app data before retrying.": "重试前请重新创建 App ID 或同步应用数据。",
    "The Apple Developer account has reached its App ID limit.": "Apple Developer 账户已达到 App ID 数量上限。",
    "Remove an unused App ID before retrying.": "重试前请移除未使用的 App ID。",
    "An app group value was rejected as invalid.": "应用组值无效，已被拒绝。",
    "Fix the app group configuration before retrying.": "重试前请修正应用组配置。",
    "A required app group does not exist on the developer team.": "开发者团队中不存在所需的应用组。",
    "Recreate the app group before retrying.": "重试前请重新创建应用组。",
    "Apple rejected the provisioning profile identifier.": "Apple 拒绝了配置描述文件标识符。",
    "Check the provisioning configuration before retrying.": "重试前请检查配置描述文件设置。",
    "The required provisioning profile no longer exists.": "所需的配置描述文件已不存在。",
    "Create the missing provisioning profile before retrying.": "重试前请创建缺少的配置描述文件。",
    "No usable device endpoint was selected for provisioning.": "尚未选择可用于配置的设备端点。",
    "Open Connection and select a working endpoint, then retry provisioning.": "请打开“连接”并选择可用端点，然后重试配置。",
    "The device is not reachable at the selected endpoint.": "无法通过所选端点连接设备。",
    "Open Connection, verify the endpoint, then retry provisioning.": "请打开“连接”检查端点，然后重试配置。",
    "The pairing file is invalid or unreadable.": "配对文件无效或无法读取。",
    "Place or import a current pairing file, then retry provisioning.": "请放置或导入当前有效的配对文件，然后重试配置。",
    "The device connection service has not started.": "设备连接服务尚未启动。",
    "Complete pairing, then retry provisioning.": "请完成设备配对，然后重试配置。",
    "A pairing file is required before this device can finish provisioning.": "此设备需要配对文件才能完成配置。",
    "Place or import a pairing file, then retry provisioning.": "请放置或导入配对文件，然后重试配置。",
    "SideStore could not identify this device for registration.": "SideStore 无法识别此设备以进行注册。",
    "Check LocalDevVPN and the pairing file, then retry provisioning.": "请检查 LocalDevVPN 和配对文件，然后重试配置。",
    "The saved Apple session is no longer valid.": "已保存的 Apple 会话已失效。",
    "Sign in again with this Apple ID, then retry provisioning.": "请使用此 Apple ID 重新登录，然后重试配置。",
    "Apple denied the provisioning request for this account.": "Apple 拒绝了此账户的配置请求。",
    "Check the account and team under Account and Signing, then retry provisioning.": "请在“账户与签名”中检查账户和团队，然后重试配置。",
    "A required app group is missing for this signing configuration.": "此签名配置缺少必需的应用组。",
    "Fix the app group configuration, then retry provisioning.": "请修正应用组配置，然后重试配置。",
    "The signing certificate Apple holds for this app was revoked.": "Apple 为此应用保存的签名证书已被吊销。",
    "Re-sign or reinstall the app under Certificates.": "请在“证书”中重新签名或重新安装应用。",
    "The active custom signing certificate was revoked on the Developer Portal.": "当前自定义签名证书已在开发者门户中被吊销。",
    "Select or create a current certificate under Certificates.": "请在“证书”中选择或创建有效证书。",
    "The active custom signing certificate has expired.": "当前自定义签名证书已过期。",
    "The signing certificate Apple holds for this app has expired.": "Apple 为此应用保存的签名证书已过期。",
    "The signing certificate for this app no longer matches the active certificate.": "此应用的签名证书与当前证书不匹配。",
    "A required provisioning profile is not available.": "缺少所需的配置描述文件。",
    "Open Certificates and review the active profile, then retry provisioning.": "请打开“证书”检查当前描述文件，然后重试配置。",
    "Apple rejected the provisioning request for this app.": "Apple 拒绝了此应用的配置请求。",
    "Review the app identifier and team under Account and Signing, then retry provisioning.": "请在“账户与签名”中检查应用标识符和团队，然后重试配置。",
    "The provisioning request to Apple timed out.": "向 Apple 发出的配置请求超时。",
    "Retry once. If it repeats, check the connection and try again later.": "请重试一次；如果再次发生，请检查网络并稍后再试。",
    "The connection to the Apple Developer service failed during provisioning.": "配置期间无法连接 Apple Developer 服务。",
    "Check the connection, then retry provisioning.": "请检查网络连接，然后重试配置。",
    "SideStore could not finish provisioning for a reason it does not classify.": "SideStore 无法完成配置，且无法识别具体原因。",
    "You can retry. If it keeps failing, keep the technical details and review Account and Signing and Certificates.": "您可以重试。如果问题持续，请保留技术详情并检查“账户与签名”和“证书”。",
    "This failure is not marked safe to retry. Resolve the displayed prerequisite and review Diagnostics.": "此错误不适合直接重试。请先解决显示的前置问题并查看诊断信息。",
    "Apple is limiting sign-in attempts. Wait before starting a new sign-in.": "Apple 正在限制登录尝试。请稍后再开始新的登录。",
    "This sign-in attempt ended. Start a new sign-in; Apple will request a fresh verification code after credentials are accepted.": "此次登录已结束。请重新登录；凭据通过后，Apple 会再次要求输入验证码。",
    "Apple's authentication service is temporarily unavailable. Wait for it to recover, then start a new sign-in.": "Apple 登录服务暂时不可用。请等待服务恢复后重新登录。",
    "SideStore could not obtain Anisette data. Check Anisette Servers in Settings, then start a new sign-in.": "SideStore 无法获取 Anisette 数据。请在“设置”中检查 Anisette 服务器，然后重新登录。",
    "The connection to Apple's authentication service failed. Check Connection or LocalDevVPN, then start a new sign-in.": "无法连接 Apple 登录服务。请检查“连接”或 LocalDevVPN，然后重新登录。",
    "The exact cause or retry safety could not be confirmed. Starting again creates a new attempt and may not resolve the previous failure.": "无法确认具体原因或重试是否安全。重新开始会创建新的尝试，但不一定能解决之前的问题。",
    "Resolve the account issue shown by Apple, then begin a new sign-in.": "请按照 Apple 显示的提示解决账户问题，然后重新登录。",
    "Create an app-specific password for this authentication path, then enter it in the password prompt.": "请为此登录方式创建 App 专用密码，并在密码栏中输入。",
    "This failure is not marked safe to retry. Review Diagnostics before another attempt.": "此错误不适合直接重试。再次尝试前请查看诊断信息。",
    "Wait before starting a new sign-in.": "请等待一段时间后再重新登录。",
    "Start a new sign-in; Apple will request a fresh verification code after credentials are accepted.": "请重新登录；凭据通过后，Apple 会再次要求输入验证码。",
    "Check Connection or LocalDevVPN, then start a new sign-in.": "请检查“连接”或 LocalDevVPN，然后重新登录。",

    # 4e. Unified shell, recovery dialogs, settings, and dynamic label prefixes
    "Settings": "设置",
    "What you can do": "可执行的操作",
    "What happened": "发生了什么",
    "Another refresh is already running. Refresh All will be available when it finishes.": "另一个刷新任务正在运行。完成后即可使用“全部刷新”。",
    "Start Again": "重新开始",
    "Dismiss": "忽略",
    "Version ": "版本 ",
    "Loading catalog...": "正在加载目录…",
    "Return to Sources": "返回软件源",
    "Retry Catalog": "重试加载目录",
    "Try Catalog Again (retryability unknown)": "再次尝试加载目录（是否可重试未知）",
    "Reload Catalog": "重新加载目录",
    "Expires ": "到期时间：",
    "A pairing file is required before this device can be refreshed.": "刷新此设备前需要配对文件。",
    "Refresh ": "刷新 ",
    "Progress": "进度",
    "Reconcile After Checking Device": "检查设备后核对状态",
    "I checked; restart SideStore": "我已检查；重新启动 SideStore",
    "Keep Waiting": "继续等待",
    "Use this only after confirming the device is no longer installing, updating, refreshing, or deleting the app.": "仅在确认设备已不再安装、更新、刷新或删除应用后使用此操作。",
    "Loading certificates...": "正在加载证书…",
    "Pairing file could not be read or validated": "无法读取或验证配对文件",
    "Choose Pairing File Again": "重新选择配对文件",
    "Pairing File Required": "需要配对文件",
    "Recommended setup": "推荐的设置方式",
    "If you installed with iLoader:": "如果您使用 iLoader 安装：",
    "Other installation tools use different menu names, but they all place the pairing file for the installed app.": "其他安装工具的菜单名称可能不同，但都会为已安装的应用放置配对文件。",
    "Pairing File Ready": "配对文件已就绪",
    "A valid pairing file is available. Re-check if you replace the file or reset the device.": "已找到有效配对文件。替换文件或重置设备后，请重新检查。",
    "Alternative: Import Pairing File Manually": "备用方式：手动导入配对文件",
    "Use this only if the placement tool did not work. Pick a .mobiledevicepairing or .plist file. This screen owns the picker; the service only validates and stores the file.": "仅当自动放置工具无法使用时采用此方式。请选择 .mobiledevicepairing 或 .plist 文件。文件选择器由此界面打开，后台服务只负责验证并保存文件。",
    "Not set": "未设置",
    "SideStore uses its active certificate for signing, refresh, and installation. LiveContainer keeps a separate JIT-Less certificate copy. JIT-Less certificate status does not by itself mean SideStore refresh used that copy.": "SideStore 使用其当前证书进行签名、刷新和安装。LiveContainer 会单独保存一份免 JIT 证书。免 JIT 证书状态本身并不表示 SideStore 刷新使用了该副本。",
    "Refreshing the JIT-Less copy cannot repair SideStore's active certificate.": "更新免 JIT 证书副本无法修复 SideStore 当前使用的证书。",
    "Stop Waiting": "停止等待",
    "Last verified ": "上次验证时间：",
    "Updated ": "更新时间：",
    "Starts one manual refresh and shows scheduler state through verified completion or failure.": "启动一次手动刷新，并显示计划任务状态直至刷新结果得到验证或失败。",
    "Choose an IPA to sign and install as an iOS app.": "选择一个 IPA 文件进行签名，并作为 iOS 应用安装。",
    "Remove this source?": "要移除此软件源吗？",
    "Check the device before restarting SideStore?": "重新启动 SideStore 前，请先检查设备状态。",
    "Are you sure?": "确定要继续吗？",
    "Recreate the database on next start?": "下次启动时重新创建数据库吗？",
    "Status last updated ": "状态更新时间：",
    "Reloads the latest SideStore connection and account status. This does not refresh installed apps.": "重新加载最新的 SideStore 连接和账户状态，但不会刷新已安装的应用。",
    "SideStore status: ": "SideStore 状态：",
    "Install shared app": "安装共享应用",
    "Install app": "安装应用",
    "Install ": "安装 ",
    "Enable JIT for ": "为以下应用启用 JIT：",
    "Install / Sideload App with SideStore": "使用 SideStore 安装 / 侧载应用",
    "Always Show VPN Configuration": "始终显示 VPN 配置",
    "Accept IPv6 Connections": "接受 IPv6 连接",
    "Use Local VPN": "使用本地 VPN",
    "Offline Mode": "离线模式",
    "Disable Rotation": "停用轮换",
    "On-Device Anisette": "设备端 Anisette",
    "Custom Server URL": "自定义服务器 URL",
    "Custom Anisette URL Override": "覆盖自定义 Anisette URL",
    "Customize App ID": "自定义 App ID",
    "Customize App Extensions": "自定义应用扩展",
    "Auto-Fix App Group IDs": "自动修复 App Group ID",
    "Prefer Resigned IPA": "优先使用重新签名的 IPA",
    "Export Resigned App": "导出重新签名的应用",
    "Minimuxer Gateway Backend": "Minimuxer 网关后端",
    "App Verification Disabled": "关闭应用验证",
    "Verify Bundle ID": "验证 Bundle ID",
    "Verify iOS Version": "验证 iOS 版本",
    "Verify App Version": "验证应用版本",
    "Verify Checksum": "验证校验和",
    "Verify File Size": "验证文件大小",
    "Disable Permission Checking": "停用权限检查",
    "Skip Non-Copyable Backup Files": "跳过无法复制的备份文件",
    "WireGuard EMP": "WireGuard EMP",
    "Back up ": "备份 ",
    "Restore ": "恢复 ",
    "SideJIT Server Enabled": "启用 SideJIT 服务器",
    "Server Address": "服务器地址",
    "Beta Track": "测试版更新频道",
    "Verbose Operations": "详细操作日志",
    "Verbose SideStore": "详细 SideStore 日志",
    "Verbose Signing": "详细签名日志",
    "Verbose Transport": "详细传输日志",
    "Widget Logging": "小组件日志",
    "Rotate Logs on Startup": "启动时轮换日志",
    "Disable Response Caching": "停用响应缓存",
    "Cellular Refresh": "蜂窝网络刷新",
    "Debug Mode": "调试模式",
    "Not required": "无需配置",
    "This iOS version does not require a JIT-Less certificate.": "此 iOS 版本无需免 JIT 证书。",
    "Configured / Ready": "已配置 / 就绪",
    "The LiveContainer JIT-Less certificate matches the active SideStore certificate.": "LiveContainer 的免 JIT 证书与 SideStore 当前证书一致。",
    "JIT-Less certificate copy is out of date": "免 JIT 证书副本已过期",
    "SideStore is using a different or newer signing certificate than the JIT-Less certificate stored by LiveContainer. Refresh the JIT-Less certificate copy.": "SideStore 当前使用的签名证书与 LiveContainer 保存的免 JIT 证书不同或更新。请刷新免 JIT 证书副本。",
    "No active SideStore certificate": "SideStore 没有可用证书",
    "SideStore has no active signing certificate. Open Certificates and create or select one before configuring JIT-Less.": "SideStore 没有当前签名证书。请先打开“证书”创建或选择证书，再配置免 JIT。",
    "Active certificate revoked": "当前证书已吊销",
    "SideStore's active signing certificate is reported as revoked. Open Certificates and select or create a current certificate.": "SideStore 当前签名证书已被报告为吊销。请打开“证书”并选择或创建有效证书。",
    "Active certificate expired": "当前证书已过期",
    "SideStore's active signing certificate has expired. Open Certificates and select or create a current certificate.": "SideStore 当前签名证书已过期。请打开“证书”并选择或创建有效证书。",
    "JIT-Less certificate not configured": "尚未配置免 JIT 证书",
    "LiveContainer has no JIT-Less certificate copy yet. Import one to launch guest apps on this iOS version.": "LiveContainer 尚无免 JIT 证书副本。请导入证书以在此 iOS 版本上启动容器应用。",
    "JIT-Less certificate copy is revoked": "免 JIT 证书副本已吊销",
    "The certificate stored by LiveContainer is reported as revoked. Import a current copy.": "LiveContainer 保存的证书已被报告为吊销。请导入有效副本。",
    "Certificate imported, validation pending": "证书已导入，等待验证",
    "The certificate is stored but could not be validated yet.": "证书已保存，但目前无法验证。",
    "JIT-Less certificate needs refreshing": "需要更新免 JIT 证书",
    "Refresh the JIT-Less certificate copy from SideStore.": "请从 SideStore 刷新免 JIT 证书副本。",
    "Validation unknown": "验证状态未知",
    "The JIT-Less certificate state could not be verified.": "无法验证免 JIT 证书状态。",
    "working": "进行中",
    "success": "成功",
    "warning": "警告",
    "failure": "失败",
    "cancelled": "已取消",
    "unknown": "未知",
    "Reloading Status...": "正在重新加载状态…",
    "Connected": "已连接",
    "Not Connected": "未连接",
    "Retry Source": "重试软件源",
    "Reload Sources": "重新加载软件源",
    "Open Account & Signing": "打开账户与签名",
    "Open Connection Settings": "打开连接设置",
    "Choose IPA Again": "重新选择 IPA",
    "Open Setup Assistant": "打开设置向导",
    "Open Sources": "打开软件源",
    "Sign-in timed out. SideStore reports that no account is currently signed in.": "登录已超时。SideStore 报告当前没有已登录账户。",
    "Sign-in was cancelled. SideStore reports that no account is currently signed in.": "登录已取消。SideStore 报告当前没有已登录账户。",
    "Apple ID signed in successfully. SideStore is still finishing provisioning.": "Apple ID 已成功登录。SideStore 仍在完成设备配置。",
    "Another Apple sign-in session is active. This request could not be matched to it. Wait for it to finish, then reload status.": "另一个 Apple 登录会话仍在运行，当前请求无法与之匹配。请等待其完成后重新加载状态。",
    "SideStore confirmed that no account is currently signed in. You can start a new sign-in.": "SideStore 已确认当前没有已登录账户。您可以重新开始登录。",
    "SideStore no longer has the active sign-in session. The current account and provisioning state could not be confirmed. Reload status before continuing.": "SideStore 已无法找到当前登录会话，无法确认账户和配置状态。继续前请重新加载状态。",
    "SideStore confirmed that the account is signed in.": "SideStore 已确认账户登录成功。",
    "Provisioning could not be completed because of an unexpected failure.": "发生意外错误，无法完成配置。",
    "Authentication succeeded. Continue to finish provisioning this device.": "身份验证成功。请继续完成此设备的配置。",
    "Optionally customize the bundle identifier used for signing.": "您可以选择自定义用于签名的 Bundle ID。",

    # 5. Certificates (证书管理)
    "Certificate": "证书",
    "Certificate Expiry": "证书到期时间",
    "Certificates": "证书列表",
    "Request New Certificate": "申请新证书",
    "Load Portal Certificates": "加载门户证书",
    "Revoke": "吊销",
    "Revoke Certificate": "吊销证书",
    "Revoking or deleting a certificate affects every app signed with it.": "吊销或删除证书将影响使用该证书签名的所有应用。",
    "Expires": "到期",
    "Next Expiry": "下次到期",
    "Provisioning Profiles (%lld)": "描述文件（%lld）",

    # 6. Device & Pairing (设备与配对)
    "Device": "设备",
    "Devices": "设备列表",
    "Pairing": "设备配对",
    "Pairing File": "配对文件",
    "Pairing Status": "配对状态",
    "Import Pairing File": "导入配对文件",
    "Pick a .mobiledevicepairing or .plist file. This screen owns the picker; the service only validates and stores the file.": "请选择 .mobiledevicepairing 或 .plist 配对文件。系统仅会验证并安全存储该文件。",
    "The picker belongs to this screen; the service only parses and stores the file.": "文件选择器由此界面直接调用；后台服务仅负责解析与安全存储该文件。",
    "Remote Pairing Port Override (0 = default)": "远程配对端口覆盖（0 为默认）",

    # 7. Network & Anisette (网络与 Anisette)
    "Network": "网络环境",
    "Connection": "网络连接",
    "Server": "服务器",
    "Servers (%lld)": "服务器列表（%lld）",
    "Anisette Servers": "Anisette 服务器",
    "Use This Server": "使用此服务器",
    "Test Reachability": "测试连通性",
    "Reconnect to SideStore": "重新连接 SideStore",
    "Daemon Health": "守护进程健康状态",
    "Health": "健康状态",
    "Health Check": "健康检查",

    # 8. Refresh & Scheduler (自动续签与计划)
    "Automatic Refresh": "自动刷新",
    "Background Refresh": "后台刷新",
    "Scheduled refresh": "定时计划刷新",
    "SideStore refresh": "SideStore 自动续签",
    "Refresh": "刷新",
    "Refresh All": "全部刷新",
    "Refresh Deadline": "刷新截止期限",
    "Refresh SideStore now": "立即刷新 SideStore",
    "Last Refresh Warning": "上次刷新警告",
    "Last Verified Run": "上次成功验证运行",
    "Last result": "上次结果",
    "History": "历史记录",
    "No refreshes recorded": "暂无刷新记录",
    "Copy Refresh Diagnostics": "复制刷新诊断",
    "Allow Notifications": "允许通知",
    "Allow Refresh Notifications": "允许刷新通知",
    "Allow refresh notifications": "允许刷新通知",
    "Notifications": "通知设置",
    "Enable optional deadline alarm": "启用截止期限提醒闹钟",
    "A weekly schedule can be too late for free-account signing. Prefer daily refresh.": "对于免费个人开发者证书，每周刷新可能过慢，建议使用每日刷新。",
    "Refresh can start before the target time to allow for iOS scheduling delays.": "刷新可能会在目标时间稍早开始，以适应 iOS 系统后台调度延迟。",
    "Background execution remains best-effort. A scheduled request is not a completed refresh.": "系统后台执行为尽力而为模式。已安排的任务并不代表已完成刷新。",
    "Swipe right to reveal Delete, or use Select to delete several entries. Deleting history does not change refresh status or scheduled tasks.": "右滑可显示删除选项，或使用“选择”批量删除条目。删除历史记录不会改变刷新状态或已安排的任务。",
    "This deletes history entries only. Refresh settings and the current signing status are not changed.": "此操作仅删除历史记录条目，不会更改刷新设置或当前签名状态。",
    "Warnings": "警告通知",
    "Warnings require permission. A deadline warning asks you to check an unconfirmed refresh; it cannot diagnose a task that never ran.": "警告通知需要系统权限。截止警告会在未确认刷新时提醒您检查，无法排查从未运行的任务。",
    "Refresh start, completion and deadline warnings arrive as notifications.": "刷新开始、完成及截止警告将通过系统通知提醒。",
    "The previous refresh result is uncertain. Automatic retries are paused. Review app status and expiration before explicitly retrying.": "上次刷新结果存在不确定性，已暂停自动重试。请在重试前检查各应用的实际状态与到期时间。",
    "LiveContainer can notify you when a refresh starts, completes, or needs attention. Nothing runs differently if you skip this.": "LiveContainer 可以在刷新开始、完成或需要处理时向您发送通知。跳过此步骤不会影响任何功能的运行。",

    # 9. Apps & Backups (应用管理与备份)
    "Apps": "应用",
    "Apps and Data": "应用与数据",
    "Sideloaded": "侧载应用",
    "Sideloaded Apps": "侧载应用列表",
    "Selected App": "已选应用",
    "Guests": "容器应用",
    "LiveContainer Guests": "LiveContainer 容器应用",
    "Host App": "宿主应用",
    "Guest Runtime": "容器运行时",
    "Install / Sideload App": "安装 / 侧载应用",
    "Install as LiveContainer Guest": "作为 LiveContainer 容器应用安装",
    "Install with SideStore": "通过 SideStore 安装",
    "Installation Options": "安装选项",
    "This app is no longer in the library.": "此应用已不在资料库中。",
    "App Backups": "应用备份",
    "Backups": "备份管理",
    "Back Up": "备份",
    "Select Backup File": "选择备份文件",
    "Import / Export": "导入 / 导出",
    "Import from File": "从文件导入",
    "Export to File": "导出到文件",
    "App Groups": "App 群组",
    "App IDs": "App ID 标识符",
    "Sync App IDs": "同步 App ID",
    "Sync with Remote": "与远程服务器同步",
    "On This Device (%lld)": "此设备上（%lld）",
    "%lld apps": "%lld 个应用",

    # 10. Sources (软件源)
    "Sources": "软件源",
    "Sources (%lld)": "软件源（%lld）",
    "Add Source": "添加软件源",
    "Add Source and Retry": "添加软件源并重试",
    "Remove Source": "移除软件源",
    "Remove from Library": "从资料库中移除",
    "Missing Source": "缺少软件源",
    "Previously Saved Guest Sources": "历史保存的容器软件源",
    "Select a saved URL to preview and add it to the unified catalog. Existing saved URLs are preserved.": "选择已保存的 URL 预览并添加到统一目录中。原有的已存 URL 将予以保留。",
    "Apps already installed from this source stay installed, but they will no longer receive updates.": "从该源安装的应用将保留，但不再接收后续更新。",

    # 11. Advanced & Developer Features (高级与开发者特性)
    "Advanced": "高级设置",
    "Diagnostics": "诊断信息",
    "Copy Diagnostics": "复制诊断信息",
    "Logging": "日志记录",
    "Operation Logs": "操作日志",
    "Copy Logs": "复制日志",
    "Reload Logs": "重新加载日志",
    "Reload Developer Data": "重新加载开发者数据",
    "Configuration JSON": "配置 JSON",
    "SideJIT Server": "SideJIT 服务器",
    "Enable JIT": "启用 JIT",
    "SideSign Configuration": "SideSign 签名配置",
    "Services": "服务状态",
    "Set Active": "设为当前活跃",
    "Tweaks": "动态插件",
    "Recreate Database on Next Start": "下次启动时重建数据库",
    "Experimental": "实验性",
    "Experimental Features": "实验性功能",
    "Experimental options can change or disappear. Current signing state is never reset by toggling them.": "实验性选项可能会更改或移除。切换这些选项不会重置当前的签名状态。",
    "LiveContainer + SideStore": "LiveContainer + SideStore",
    "LiveContainer + SideStore unified build": "LiveContainer + SideStore 统一整合版",
    "NRG-Wardog on GitHub": "访问 NRG-Wardog GitHub 主页",

    # Dynamic format interpolations
    "Protection: %@": "防护状态：%@"
}


def patch_livecontainer(root: Path) -> None:
    print(f"[*] Applying comprehensive Chinese localization to LiveContainer: {root}")
    xcstrings_path = root / "Resources" / "Localizable.xcstrings"
    if not root.is_dir() or not xcstrings_path.is_file():
        raise SystemExit(f"[ERROR] Required LiveContainer string catalog is missing: {xcstrings_path}")
    data = json.loads(xcstrings_path.read_text(encoding="utf-8"))
    strings = data.setdefault("strings", {})
    if not isinstance(strings, dict):
        raise SystemExit(f"[ERROR] Invalid strings dictionary in {xcstrings_path}")

    added_count = 0
    updated_count = 0

    for key, zh_val in V3_TRANSLATIONS.items():
        if key not in strings:
            strings[key] = {
                "extractionState": "manual",
                "localizations": {
                    "en": {"stringUnit": {"state": "translated", "value": key}},
                    "zh-Hans": {"stringUnit": {"state": "translated", "value": zh_val}}
                }
            }
            added_count += 1
        else:
            locs = strings[key].setdefault("localizations", {})
            if not isinstance(locs, dict):
                raise SystemExit(f"[ERROR] Invalid localizations entry for {key!r} in {xcstrings_path}")
            locs["zh-Hans"] = {"stringUnit": {"state": "translated", "value": zh_val}}
            updated_count += 1

    xcstrings_path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"    Updated: {xcstrings_path.name} (added {added_count}, updated {updated_count}, total keys: {len(strings)})")
    verified = json.loads(xcstrings_path.read_text(encoding="utf-8"))
    for key, zh_val in V3_TRANSLATIONS.items():
        actual = (verified["strings"].get(key, {}).get("localizations", {})
                  .get("zh-Hans", {}).get("stringUnit", {}).get("value"))
        if actual != zh_val:
            raise SystemExit(f"[ERROR] Chinese localization verification failed for {key!r}")

    # Ensure zh-Hans.lproj exists alongside zh_CN.lproj for InfoPlist.strings
    zh_cn = root / "Resources" / "zh_CN.lproj"
    zh_hans = root / "Resources" / "zh-Hans.lproj"
    if zh_cn.is_dir() and not zh_hans.exists():
        shutil.copytree(zh_cn, zh_hans)
        print(f"    Created: {zh_hans} from zh_CN")


def patch_sidestore(root: Path) -> None:
    print(f"[*] Applying Chinese localization to SideStore: {root}")
    project = root / "AltStore.xcodeproj" / "project.pbxproj"
    if not root.is_dir() or not project.is_file():
        raise SystemExit(f"[ERROR] Embedded SideStore project is missing: {project}")
    project_text = project.read_text(encoding="utf-8")
    if "PBXFileSystemSynchronizedRootGroup" not in project_text or "path = AltStore;" not in project_text:
        raise SystemExit(f"[ERROR] SideStore AltStore resources are not included by a synchronized Xcode group: {project}")

    # The pinned SideStore project has a synchronized AltStore root group but
    # no Resources directory in its clean source tree. Create it so Xcode adds
    # the localized strings resource to the SideStore target automatically.
    altstore_res = root / "AltStore" / "Resources"
    altstore_res.mkdir(parents=True, exist_ok=True)
    zh_lproj = altstore_res / "zh-Hans.lproj"
    zh_lproj.mkdir(parents=True, exist_ok=True)
    strings_file = zh_lproj / "Localizable.strings"

    lines = [
        "/* SideStore Simplified Chinese Localization (Non-destructive external strings) */\n"
    ]
    for k, v in sorted(V3_TRANSLATIONS.items()):
        escaped_k = k.replace('"', '\\"').replace("\n", "\\n")
        escaped_v = v.replace('"', '\\"').replace("\n", "\\n")
        lines.append(f'"{escaped_k}" = "{escaped_v}";\n')

    strings_file.write_text("".join(lines), encoding="utf-8")
    print(f"    Generated: {strings_file} ({len(V3_TRANSLATIONS)} entries)")


def main() -> None:
    if len(sys.argv) < 3:
        print("Usage: apply_bilingual_localization.py <path_to_LiveContainer> <path_to_EmbeddedSideStore>")
        sys.exit(1)

    lc_root = Path(sys.argv[1]).resolve()
    ss_root = Path(sys.argv[2]).resolve()

    patch_livecontainer(lc_root)
    patch_sidestore(ss_root)
    print("[SUCCESS] Comprehensive bilingual localization applied successfully.")


if __name__ == "__main__":
    main()
